<?php

namespace Database\Seeders;

use App\Models\CodeCashBook;
use App\Models\PaymentStatus;
use App\Models\PickupStatus;
use App\Models\Status;
use App\Models\User;
use App\Models\WasteBank;
use App\Models\WasteType;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        WasteType::create(['title' => 'kertas', 'range_price' => '1000-2000']);
        WasteType::create(['title' => 'besi', 'range_price' => '1000-2000']);
        WasteType::create(['title' => 'plastik', 'range_price' => '1000-2000']);

        WasteBank::create(['name' => 'BANK SAMPAH MAWAR PUTIH', 'address' => '']);
        WasteBank::create(['name' => 'BANK SAMPAH SUMBER REJEKI', 'address' => '']);
        WasteBank::create(['name' => 'BAROKAH JAYA WASTE LAB', 'address' => '']);

        PickupStatus::create(['title' => 'belum dijemput']);
        PickupStatus::create(['title' => 'gagal dijemput']);
        PickupStatus::create(['title' => 'sudah dijemput']);

        User::create([
            'name' => 'admin',
            'email' => 'admin@admin',
            'password' => bcrypt('admin'),
            'role' => 1,
            'phone' => '082335456772',
            'address' => 'Jalan tawang mangu gg. 6 no. 10'
        ]);
        $no_customer = [
            10110,
            20105,
            30105,
            40105,
            50105,
            60105,
            70105,
            80105,
            90105,
            100105,
            110105,
            120105,
            130105,
            10203,
            20203,
            30203,
            40203,
            50203,
            350202,

            10301,
            20301,
            30301,
            40301,
            50301,
            60301,
            70301,
            80301,
            90301,
            100301,
            110301,
            120301,
            130301,
            140301,
            150301,
            160301,
            170201,

            10302,
            20302,
            30302,
            40302,
            50302,
            60302,
            70302,
            80302,
            90302,
            100302,
            110302,
            120302,
            130302,
            140302,
            150302,
            160302,
            170302,
            180302,
            190302,
            200302,
            210302,
            220302,
            230302,
            240302,
            250302,
            260302,
            270302,
            280302,
            290302,
            300302,
            310302,
            320302,
            330302,
            340302,

            10303,
            20303,
            30303,
            40303,
            50303,
            60303,
            70303,
            80303,
            90303,
            100303,
            110303,
            120303,
            130303,
            140303,
            150303,
            160303,
            170303,
            180303,
            60203,

            10304,
            20304,
            30304,
            40304,
            50304,
            60304,
            70304,
            80304,
            90304,
            100304,
            110304,
            120304,
            130304,

            10406,
            20406,
            30406,
            40406,
            50406,
            60406,
            70406,
            80406,
            90406,
            100406,
            110406,
            120406,
            130406,
            140406,
            150406,
            160406,
            170406,
            180406,
            190406,
            200406,
            210406,
            220406,
            230406,
            240406,
            250406,
            260406,
            270406,
            280406,
            290406,
            300406,
            310406,
            320406,
            330406,
            340406,
            350406,
            360406,
            370406,
            380407,
            390407,

            10507,
            20507,
            30507,

            10609,
            20609,
            30608,
            40608,
            50608,
            60608,

            10707,
            20707,
            30707,
            40706
        ];
        $name = [
            'Sukarnoto',
            'Rohmat',
            'Suparman',
            'Imam Taukhid',
            'Basuki Rohmad',
            'Ismail',
            'Saimin',
            'Abd Rozak',
            'Shohibul Ulum',
            'Lisanto',
            'Rudi Tarzikin',
            'Jasim Suryanto',
            'Iwan Sunaryo',
            'Muchlis',
            'Abu Khoirun',
            'Sugeng Winoto',
            'Suprapto',
            'Ahmad Zaini',
            'Darminto',

            'Budiono',
            'Siran',
            'Hadi Sukatno',
            'Khoironi',
            'Kadeni',
            'Yusuf',
            'Markuwat',
            'Bastomi',
            'Muhammad Tohari',
            'Khoirul Anam',
            'Rukun',
            'Sumardi',
            'Nanang Bintoro',
            'Suharto',
            'Tatok Nilyanto',
            'Sukirno Wardoyo',
            'Samsul Arifin',

            'Muhammad Syaiful Anam',
            'Misnanto',
            'Ngatimin',
            'Sarimun',
            'Tumiran',
            'Supriyanto',
            'Anwar Jauhari',
            'Ponisan Efendi',
            'Hasim Asari',
            'Muhaimin',
            'Yahno',
            'Kliwon Subiyanto',
            'Nurul Anam',
            'Sumadi',
            'Tumirin',
            'Muhammad Syamsul Arifin',
            'Imam Rofii',
            'Sudiono',
            'Sudaryo',
            'Sukiyan',
            'Sunardi',
            'Hariyadi Sunyoto',
            'Hariyanto/wiro',
            'Siswanto',
            'Slamet Riyadi',
            'Sumari',
            'Tumari',
            'Jemani',
            'Agus ansori',
            'Suwandi',
            'Ismaun',
            'Hendra Prasetyo',
            'Budiono',
            'Budi Catur Prasetya',

            'Sujarkoni',
            'Sugianto',
            'Solekan',
            'Imam Bastomi',
            'Muhammad Zainuri',
            'Basori',
            'Yaman',
            'Sinto',
            'M. Maruf',
            'Farianto',
            'Sandy Pradana Putra',
            'Sugiman Hadi Siswanto',
            'Darwanto',
            'Wahyu Utomo',
            'Jaedun',
            'Suyut',
            'Mohammad Nuril Huda',
            'Jemani',
            'Imam Baedowi',

            'Moh. Jaelani',
            'M. Yaskur',
            'Ahmad Taufik',
            'Suwondo',
            'Dadang Prihandoko',
            'Kateni',
            'Ahmad Ihsan Saiful Rizal',
            'Ahmad Kholil',
            'Ahmad Zaeni',
            'Marsono',
            'Subarno',
            'Mahfudz Effendi',
            'Amin Tohari',

            '            Purwanto',
            'M. Nafik',
            'Nanang Qosim',
            'Suyadi',
            'Muhammad Fauzi',
            'Ernawati',
            'Abd Azis',
            'Muat',
            'Asnawi',
            'Katmiadi',
            'Sumardi',
            'Nikmat',
            'Sugianto',
            'Imam Bukhori',
            'Muhammad Musawir',
            'Abd Hamid',
            'Mulyadi',
            'Urip',
            'Edi Subiyantoro',
            'Imam Ashari',
            'Sanidin',
            'Zainul Wafa',
            'Imam Suwandi',
            'Humaidi Lutvi',
            'Sholihin',
            'Sugianto',
            'Saiful Anam',
            'Taufik Qurrohman',
            'Samsul Arifin',
            'Budiono',
            'Nur Hasyim',
            'Supandi',
            'Saifulloh',
            'Sholeh',
            'Samsul Arifin',
            'Kasiyanto',
            'Hasan Basri',
            'Mualip',
            'Muhammad Rofiq',

            'Romli',
            'Misran',
            'Toher',

            'Maskuri',
            'Sumar',
            'Supadiono',
            'Slamet Riyanto',
            'H. Ahmat Yasin',
            'Hasan Basri',

            'Muhammad Ali',
            'Edy Siswanto',
            'Zainal Arifin',
            'M. Kasturi',
        ];
        $master = [
            'Agus Salim',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Iwan Sunaryo',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Misnanto',

            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',
            'Sukirno Wardoyo',

            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',
            'Misnanto',

            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',
            'Ahmad Zaini',

            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',
            'Amin Tohari',

'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'Urip',
'M.Ali',
'M.Ali',

'M.Ali',
'M.Ali',
'M.Ali',

'M. Ali Wafa',
'M. Ali Wafa',
'Slamet Riyanto',
'Slamet Riyanto',
'Slamet Riyanto',
'Slamet Riyanto',

'Muhammad Ali',
'Muhammad Ali',
'Muhammad Ali',
'Urip',
        ];
        $address = [
            'Dusun Karang Templek RT.003 RW.018 Andongsari',
            'Dusun Karang Templek RT.003 RW.014 Andongsari',
            'Dusun Karang Templek RT.001 RW.020 Andongsari',
            'Dusun Karang Templek RT.001 RW.020 Andongsari',
            'Dusun Karang Templek RT.001 RW.022 Andongsari',
            'Dusun Karang Templek RT.001 RW.019 Andongsari',
            'Dusun Karang Templek RT.001 RW.019 Andongsari',
            'Dusun Karang Templek RT.002 RW.019 Andongsari',
            'Dusun Karang Templek RT.002 RW.020 Andongsari',
            'Dusun Karang Templek RT.00 RW.020 Andongsari',
            'Dusun Karang Templek RT.002 RW.020 Andongsari',
            'Dusun Karang Templek RT.001 RW.020 Andongsari',
            'Dusun Krajan RT.003 RW.003 Sidodadi',
            'Dusun Kebonsari RT.003 RW.004 Sabrang Ambulu',
            'Dusun Kebonsari RT.003 RW.004 Sabrang Ambulu',
            'Dusun Kebonsari RT.003 RW.002 Sabrang Ambulu',
            'Dusun Krajan RT.001 RW.011 Sabrang Ambulu',
            'Dusun Sabrang RT.003 RW.017 Sabrang Ambulu',
            'Dusun Bedengan RT.002 RW.003 Sabrang',

            'Dusun Tegal Banteng RT.008 RW.006 Kesilir',
            'Dusun Tegal Banteng RT.005 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.006 RW.006 Kesilir',
            'Dusun Tegal Banteng RT.009 RW.006 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.006 Kesilir',
            'Dusun Tegal Banteng RT.002 RW.007 Kesilir',
            'Dusun Tegal Banteng RT.001 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.001 RW.007 Kesilir',
            'Dusun Tegal Banteng RT.005 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.007 RW.007 Kesilir',
            'Dusun Tegal Banteng RT.007 RW.007 Kesilir',
            'Dusun Tegal Banteng RT.007 RW.007 Kesilir',
            'Dusun Tegal Banteng RT.003 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.007 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.002 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.001 RW.007 Kesilir',
            'Dusun Tegal Rejo RT.002 RW.022 Sabrang',

            'Dusun Krajan RT.008 RW.002 Kesilir',
            'Dusun Krajan RT.006 RW.002 Kesilir',
            'Dusun Demangan RT.007 RW.013 Kesilir',
            'Dusun Krajan RT.003 RW.003 Kesilir',
            'Dusun Krajan RT.006 RW.004 Kesilir',
            'Dusun Krajan RT.004 RW.003 Kesilir',
            'Dusun Krajan RT.001 RW.004 Kesilir',
            'Dusun Krajan RT.008 RW.001 Kesilir',
            'Dusun Krajan RT.009 RW.004 Kesilir',
            'Dusun Tegal Banteng RT.010 RW.001 Kesilir',
            'Dusun Tegal Banteng RT.005 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.004 Kesilir',
            'Dusun Tegal Banteng RT.006 RW.008 Kesilir',
            'Dusun Bedengan RT.003 RW.014 Kesilir',
            'Dusun Demangan RT.003 RW.011 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.004 Kesilir',
            'Dusun Demangan RT.007 RW.003 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.002 RW.001 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.006 Kesilir',
            'Dusun Tegal Banteng RT.003 RW.005 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.008 Kesilir',
            'Dusun Tegal Banteng RT.004 RW.005 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.006 Kesilir',
            'Dusun Demangan RT.003 RW.011 Kesilir',
            'Dusun Krajan RT.006 RW.003 Kesilir',
            'Dusun Krajan RT.002 RW.003 Kesilir',
            'Dusun Krajan RT.003 RW.003 Kesilir',
            'Dusun Krajan Lor',
            'Dusun Tegal Banteng RT.008 RW.006 Kesilir',
            'Dusun Krajan RT.002 RW.002 Kesilir',

            'Dusun Demangan RT.001 RW.009 Kesilir',
            'Dusun Krajan RT.003 RW.002 Kesilir',
            'Dusun Demangan RT.005 RW.012 Kesilir',
            'Dusun Demangan RT.005 RW.012 Kesilir',
            'Dusun Demangan RT.007 RW.011 Kesilir',
            'Dusun Tegal Banteng RT.004 RW.007 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.005 Kesilir',
            'Dusun Demangan RT.003 RW.013 Kesilir',
            'Dusun Demangan RT.007 RW.009 Kesilir',
            'Dusun Demangan RT.002 RW.014 Kesilir',
            'Dusun Demangan RT.003 RW.012 Kesilir',
            'Dusun Demangan RT.008 RW.009 Kesilir',
            'Dusun Demangan RT.004 RW.013 Kesilir',
            'Dusun Demangan RT.008 RW.010 Kesilir',
            'Dusun Demangan RT.RT.001 RW.009 Kesilir',
            'Dusun Demangan RT.008 RW.010 Kesilir',
            'Dusun Demangan RT.001 RW.011 Kesilir',
            'Dusun Tegal Banteng RT.005 RW.007 Kesilir',
            'Dusun Tegalrejo RT.001 RW.020 Sabrang',
            ''
            , 'Dusun Demangan RT.004 RW.013 Kesilir',
            'Dusun Demangan RT.001 RW.006 Kesilir',
            'Dusun Krajan RT.005 RW.004 Kesilir',
            'Dusun Krajan RT.007 RW.003 Kesilir',
            'Dusun Tegal Banteng RT.008 RW.008 Kesilir',
            'Dusun Demangan RT.008 RW.009 Kesilir',
            'Dusun Krajan RT.005 RW.004 Kesilir',
            'Dusun Demangan RT.002 RW.011 Kesilir',
            'Dusun Demangan RT.008 RW.009 Kesilir',
            'Dusun Demangan RT.002 RW.009 Kesilir',
            'Dusun Demangan RT.002 RW.011 Kesilir',
            'Dusun Krajan RT.003 RW.004 Kesilir',
            'Dusun Krajan RT.002 RW.002 Ampel',

            'Dusun Kedung Sumur RT.004 RW.004 Bagon',
            'Dusun Kedung Sumur RT.004 RW.001 Bagon',
            'Dusun Krajan RT.005 RW.003 Bagon',
            'Dusun Kedung Sumur RT.001 RW.004 Bagon',
            'Dusun Kedung Sumur RT.004 RW.004 Bagon',
            'Dusun Kedung Sumur RT.004 RW.004 Bagon',
            'Dusun Kedung Sumur RT.004 RW.001 Bagon',
            'Dusun Kedung Sumur RT.004 RW.001 Bagon',
            'Dusun Kedung Sumur RT.004 RW.001 Bagon',
            'Dusun Kedung Sumur RT.001 RW.004 Bagon',
            'Dusun Kedung Sumur RT.004 RW.004 Bagon',
            'Dusun Kedung Sumur RT.004 RW.001 Bagon',
            'Dusun Kedung Sumur RT.002 RW.004 Bagon',
            'Dusun Kedung Sumur RT.002 RW.005 Bagon',
            'Dusun Kedung Sumur RT.002 RW.005 Bagon',
            'Dusun Kedung Sumur RT.002 RW.005 Bagon',
            'Dusun Krajan RT.005 RW.003 Bagon',
            'Dusun Kedung Sumur RT.002 RW.005 Bagon',
            'Dusun Kedung Sumur RT.037 RW.013 Bagon',
            'Dusun Kedung Sumur RT.003 RW.013 Bagon',
            'Dusun Kedung Sumur RT.002 RW.005 Bagon',
            'Dusun Kedung Sumur RT.003 RW.015 Bagon',
            'Dusun Kedung Sumur RT.003 RW.005 Bagon',
            'Dusun Kedung Sumur RT.003 RW.005 Bagon',
            'Dusun Kedung Sumur RT.002 RW.013 Bagon',
            'Dusun Kedung Sumur RT.002 RW.005 Bagon',
            'Dusun Kedung Sumur RT.003 RW.005 Bagon',
            'Dusun Kedung Sumur RT.003 RW.005 Bagon',
            'Dusun Kedung Sumur RT.003 RW.005 Bagon',
            'Dusun Kedung Sumur RT.002 RW.006 Bagon',
            'Dusun Kedung Sumur RT.002 RW.005 Bagon',
            'Dusun Kedung Sumur RT.002 RW.006 Bagon',
            'Dusun Kedung Sumur RT.002 RW.005 Bagon',
            'Dusun Kedung Sumur RT.003 RW.005 Bagon',
            'Dusun Kedung Sumur RT.002 RW.005 Bagon',
            'Dusun Krajan Bagon',
            'Dusun Kedung Sumur RT.003 RW.005 Bagon',
            'Dusun Kedung Sumur RT.003 RW.004 Bagon',
            'Dusun Krajan 2 RT.001 RW.003 Bagon (Kasian)',

            'Dusun Karang Anyar RT.001 RW.001 Balung Lor Balung',
            'Dusun Karang Anyar RT.001 RW.001 Balung Lor Balung',
            'Dusun Karang Anyar RT.002 RW.001 Balung Lor Balung',

            'DusunKrajanSembungan RT.001 RW.019 Mlokorejo',
            'DusunKrajanSembungan RT.002 RW.017 Mlokorejo',
            'DusunKrajanSembungan RT.003 RW.016 Mlokorejo',
            'DusunKrajanBarat RT.003 RW.006 Mlokorejo',
            'DusunKrajan RT.003 RW.018 Mlokorejo',
            'DusunKedungSumur RT.003 RW.005 Mlokorejo',

            'DusunKrajan  RT.002 RW.001 Jambearum',
            'DusunKrajan  RT.001 RW.001 Jambearum',
            'Dusun Kedung Sumur RT.003 RW.004 Jambearum',
            'Dusun Kedung Sumur RT.001 RW.005 Jambearum',
        ];
        $wb = [
           19,83
        ];
        $wbi=1;
        for ($i = 0; $i < count($master); $i++) {
            if ($i==19){
                $wbi=2;
            }
            if ($i==19+83){
                $wbi=3;
            }
            User::create(['waste_bank_id' => $wbi, 'name' => $name[$i], 'no_customer' => $no_customer[$i], 'master_name' => $master[$i], 'email' => $i . '@gmail.com', 'address' => $address[$i], 'password' => bcrypt('password')]);
        }

    }
}
